### ISSUE TITLE
Issue (This Activity already has an action bar supplied by the window decor.)

### ISSUE THREAD

**Issue by nurulHidayat22** [veritrans/veritrans-android#365]
Mohon bantuannya. saya menggunakan versi 1.3.1 sandbox

Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead. at android.support.v7.app.AppCompatDelegateImplV9.setSupportActionBar(AppCompatDelegateImplV9.java:203)                                                                               at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:130)                                                                               at

**Comment by dindatisi** [comment]
hi @nurulHidayat22 please email to support@midtrans.com for assistance ya. thanks
